-- Shared state for the generated Data files, which run right after this one.
-- Each Data file is a copy of a SavedVariables file from WTF, generated by tools/sync.ps1.
SVShim = { account = 0, character = 0, skipped = {} }

local function Normalize(text)
	return (text or ""):gsub(" ", "-")
end

-- Per-character Data files are wrapped in SVShim.Match(realmFolder, characterFolder).
-- WTF names character folders "First-Last" and this client names realm folders by ID.
function SVShim.Match(realm, character)
	if Normalize(UnitName("player")) ~= character then
		return false
	end
	local realmID = GetRealmID and tostring(GetRealmID())
	local realmName = GetRealmName and GetRealmName()
	if realm == realmID or realm == realmName or realm == Normalize(realmName) then
		return true
	end
	SVShim.skipped[#SVShim.skipped + 1] = realm .. "/" .. character
	return false
end
