-- Shared state for the generated Data files, which run right after this one.
-- Each Data file wraps a copy of a SavedVariables file from WTF, generated by tools/sync.ps1.
SVShim = { account = 0, character = 0, loadedByGame = {}, skipped = {}, pending = {}, applied = {} }

local function Normalize(text)
	return (text or ""):gsub(" ", "-")
end

-- WTF names character folders "First-Last", and this client's realm folder names (e.g. "70")
-- don't match the realm's ID or name, so a character name found under only one realm folder
-- (unique) is matched by name alone.
function SVShim.Match(realm, character, unique)
	if Normalize(UnitName("player")) ~= character then
		return false
	end
	if unique then
		return true
	end
	local realmID = GetRealmID and tostring(GetRealmID())
	local realmName = GetRealmName and GetRealmName()
	if realm == realmID or realm == realmName or realm == Normalize(realmName) then
		return true
	end
	SVShim.skipped[#SVShim.skipped + 1] = realm .. "/" .. character
	return false
end

-- build() assigns this file's globals. Running it under its own environment collects those
-- values instead, so the shim can compare what it would restore against what is already loaded
-- without assigning anything.
local function Capture(build)
	if not setfenv then
		return nil -- No way to collect the values without assigning them; restore unconditionally.
	end
	local captured = setmetatable({}, { __index = _G })
	setfenv(build, captured)
	local ok, err = pcall(build)
	setfenv(build, _G)
	if not ok then
		geterrorhandler()(err)
		return nil
	end
	return captured
end

-- rawget: captured falls back to _G for anything the file didn't assign.
local function Same(a, b)
	if a == b then
		return true
	end
	if type(a) ~= "table" or type(b) ~= "table" then
		return false
	end
	for key, value in pairs(a) do
		if not Same(value, rawget(b, key)) then
			return false
		end
	end
	for key in pairs(b) do
		if rawget(a, key) == nil then
			return false
		end
	end
	return true
end

-- names lists the globals build() assigns. realm/character/unique are set for per-character
-- files. build() runs once now, for addons that read their settings while their files load
-- (LoadSavedVariablesFirst), and the data is applied again at the addon's ADDON_LOADED, which is
-- when the client normally restores it, so file-level defaults like `NecrosisConfig = {}` don't
-- wipe it.
function SVShim.Register(addon, names, build, realm, character, unique)
	local isCharacter = realm ~= nil
	if isCharacter and not SVShim.Match(realm, character, unique) then
		return
	end
	build()
	for _, name in ipairs(names) do
		SVShim.applied[name] = _G[name]
	end
	local entries = SVShim.pending[addon] or {}
	entries[#entries + 1] = { names = names, build = build, isCharacter = isCharacter }
	SVShim.pending[addon] = entries
end

-- The client loads some addons' SavedVariables and skips others, so this is decided per file:
-- a live table matching this file's copy was loaded by the game (or is still the shim's own copy),
-- and anything else is the addon's own defaults, which the shim overwrites.
local function Apply(entry)
	local captured = Capture(entry.build)
	if not captured then
		entry.build()
		return true, false
	end

	local restore, fromGame = false, false
	for _, name in ipairs(entry.names) do
		local live = _G[name]
		if live ~= nil and live == SVShim.applied[name] then
			-- Still the copy this shim applied while loading; nothing touched it.
		elseif Same(live, rawget(captured, name)) then
			fromGame = true
		else
			restore = true
		end
	end

	if restore then
		for _, name in ipairs(entry.names) do
			local value = rawget(captured, name)
			if value ~= nil then
				_G[name] = value
				SVShim.applied[name] = value
			end
		end
		return true, false
	end
	return not fromGame, fromGame
end

-- !!SVShim loads first, so this handler runs before any other addon's ADDON_LOADED handler.
local frame = CreateFrame("Frame")
frame:RegisterEvent("ADDON_LOADED")
frame:SetScript("OnEvent", function(_, _, addon)
	local entries = SVShim.pending[addon]
	if not entries then
		return
	end
	SVShim.pending[addon] = nil
	for _, entry in ipairs(entries) do
		local shimProvided, gameLoaded = Apply(entry)
		if gameLoaded then
			SVShim.loadedByGame[#SVShim.loadedByGame + 1] = addon
		elseif shimProvided then
			if entry.isCharacter then
				SVShim.character = SVShim.character + 1
			else
				SVShim.account = SVShim.account + 1
			end
		end
	end
end)
