-- Shared state for the generated Data files, which run right after this one.
-- Each Data file wraps a copy of a SavedVariables file from WTF, generated by tools/sync.ps1.
SVShim = { account = 0, character = 0, skipped = {}, pending = {} }

local function Normalize(text)
	return (text or ""):gsub(" ", "-")
end

-- WTF names character folders "First-Last", and this client's realm folder names (e.g. "70")
-- don't match the realm's ID or name, so a character name found under only one realm folder
-- (unique) is matched by name alone.
function SVShim.Match(realm, character, unique)
	if Normalize(UnitName("player")) ~= character then
		return false
	end
	if unique then
		return true
	end
	local realmID = GetRealmID and tostring(GetRealmID())
	local realmName = GetRealmName and GetRealmName()
	if realm == realmID or realm == realmName or realm == Normalize(realmName) then
		return true
	end
	SVShim.skipped[#SVShim.skipped + 1] = realm .. "/" .. character
	return false
end

-- apply() assigns the addon's saved-variable globals. realm/character/unique are set for
-- per-character files. It runs once now, for addons that read their settings while their files
-- load (LoadSavedVariablesFirst), and again at the addon's ADDON_LOADED, which is when the client
-- normally restores them, so file-level defaults like `NecrosisConfig = {}` don't wipe them.
function SVShim.Register(addon, apply, realm, character, unique)
	local isCharacter = realm ~= nil
	if isCharacter and not SVShim.Match(realm, character, unique) then
		return
	end
	apply()
	local entries = SVShim.pending[addon] or {}
	entries[#entries + 1] = { apply = apply, isCharacter = isCharacter }
	SVShim.pending[addon] = entries
end

-- !!SVShim loads first, so this handler runs before any other addon's ADDON_LOADED handler.
local frame = CreateFrame("Frame")
frame:RegisterEvent("ADDON_LOADED")
frame:SetScript("OnEvent", function(_, _, addon)
	local entries = SVShim.pending[addon]
	if not entries then
		return
	end
	SVShim.pending[addon] = nil
	for _, entry in ipairs(entries) do
		entry.apply()
		if entry.isCharacter then
			SVShim.character = SVShim.character + 1
		else
			SVShim.account = SVShim.account + 1
		end
	end
end)
